// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again:
// With a Flutter package, run `flutter pub run build_runner build`.
// With a Dart package, run `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'models/clinical_atom.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
      id: const obx_int.IdUid(1, 4839671412030688402),
      name: 'ClinicalAtom',
      lastPropertyId: const obx_int.IdUid(7, 3186489064714288677),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 3288933182053715024),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 6314514369428770977),
            name: 'type',
            type: 9,
            flags: 2048,
            indexId: const obx_int.IdUid(1, 8476597014486933417)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 3435304098307673017),
            name: 'name',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 8865704044950156852),
            name: 'value',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 103882922644610242),
            name: 'unit',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 8738036112024564513),
            name: 'date',
            type: 9,
            flags: 2048,
            indexId: const obx_int.IdUid(2, 1459313797680315671)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 3186489064714288677),
            name: 'metadataJson',
            type: 9,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[])
];

/// Shortcut for [Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore(
    {String? directory,
    int? maxDBSizeInKB,
    int? maxDataSizeInKB,
    int? fileMode,
    int? maxReaders,
    bool queriesCaseSensitiveDefault = true,
    String? macosApplicationGroup}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(getObjectBoxModel(),
      directory: directory ?? (await defaultStoreDirectory()).path,
      maxDBSizeInKB: maxDBSizeInKB,
      maxDataSizeInKB: maxDataSizeInKB,
      fileMode: fileMode,
      maxReaders: maxReaders,
      queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
      macosApplicationGroup: macosApplicationGroup);
}

/// Returns the ObjectBox model definition for this project for use with
/// [Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
      entities: _entities,
      lastEntityId: const obx_int.IdUid(1, 4839671412030688402),
      lastIndexId: const obx_int.IdUid(2, 1459313797680315671),
      lastRelationId: const obx_int.IdUid(0, 0),
      lastSequenceId: const obx_int.IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, obx_int.EntityDefinition>{
    ClinicalAtom: obx_int.EntityDefinition<ClinicalAtom>(
        model: _entities[0],
        toOneRelations: (ClinicalAtom object) => [],
        toManyRelations: (ClinicalAtom object) => {},
        getId: (ClinicalAtom object) => object.id,
        setId: (ClinicalAtom object, int id) {
          object.id = id;
        },
        objectToFB: (ClinicalAtom object, fb.Builder fbb) {
          final typeOffset = fbb.writeString(object.type);
          final nameOffset = fbb.writeString(object.name);
          final valueOffset = fbb.writeString(object.value);
          final unitOffset = fbb.writeString(object.unit);
          final dateOffset = fbb.writeString(object.date);
          final metadataJsonOffset = fbb.writeString(object.metadataJson);
          fbb.startTable(8);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, typeOffset);
          fbb.addOffset(2, nameOffset);
          fbb.addOffset(3, valueOffset);
          fbb.addOffset(4, unitOffset);
          fbb.addOffset(5, dateOffset);
          fbb.addOffset(6, metadataJsonOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final typeParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final nameParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 8, '');
          final valueParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 10, '');
          final unitParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 12, '');
          final dateParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 14, '');
          final metadataJsonParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 16, '');
          final object = ClinicalAtom(
              type: typeParam,
              name: nameParam,
              value: valueParam,
              unit: unitParam,
              date: dateParam,
              metadataJson: metadataJsonParam)
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

          return object;
        })
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [ClinicalAtom] entity fields to define ObjectBox queries.
class ClinicalAtom_ {
  /// see [ClinicalAtom.id]
  static final id =
      obx.QueryIntegerProperty<ClinicalAtom>(_entities[0].properties[0]);

  /// see [ClinicalAtom.type]
  static final type =
      obx.QueryStringProperty<ClinicalAtom>(_entities[0].properties[1]);

  /// see [ClinicalAtom.name]
  static final name =
      obx.QueryStringProperty<ClinicalAtom>(_entities[0].properties[2]);

  /// see [ClinicalAtom.value]
  static final value =
      obx.QueryStringProperty<ClinicalAtom>(_entities[0].properties[3]);

  /// see [ClinicalAtom.unit]
  static final unit =
      obx.QueryStringProperty<ClinicalAtom>(_entities[0].properties[4]);

  /// see [ClinicalAtom.date]
  static final date =
      obx.QueryStringProperty<ClinicalAtom>(_entities[0].properties[5]);

  /// see [ClinicalAtom.metadataJson]
  static final metadataJson =
      obx.QueryStringProperty<ClinicalAtom>(_entities[0].properties[6]);
}
