import 'package:path/path.dart' as p;
import 'package:path_provider/path_provider.dart';
import '../models/clinical_atom.dart';
import '../objectbox.g.dart'; // This file will be generated by build_runner

class ObjectBoxService {
  late final Store store;
  late final Box<ClinicalAtom> atomBox;

  ObjectBoxService._create(this.store) {
    atomBox = Box<ClinicalAtom>(store);
  }

  /// Create an instance of ObjectBox to use throughout the app.
  static Future<ObjectBoxService> create() async {
    final docsDir = await getApplicationDocumentsDirectory();
    final store = await openStore(directory: p.join(docsDir.path, "curenet-clinical-db"));
    return ObjectBoxService._create(store);
  }

  void saveAtom(ClinicalAtom atom) {
    atomBox.put(atom);
  }

  void saveAtoms(List<ClinicalAtom> atoms) {
    atomBox.putMany(atoms);
  }

  List<ClinicalAtom> getAllAtoms() {
    return atomBox.getAll();
  }

  List<ClinicalAtom> findAtomsByType(String type) {
    final query = atomBox.query(ClinicalAtom_.type.equals(type)).build();
    final results = query.find();
    query.close();
    return results;
  }

  void clearAll() {
    atomBox.removeAll();
  }
}
